breakfasts/config/routes.rb
Rails.application.routes.draw do
  resources :trail_mixes

  resources :breakfasts

end

breakfasts/app/models/breakfast.rb
class Breakfast < ActiveRecord::Base

  validates :name, presence: true, length: { minimum: 2 }
  validates :description, presence: true, length: { minimum: 15 }
  validates :image_url, presence: {message: "YOU suck" }
end

breakfasts/app/models/trail_mix.rb
class TrailMix < ActiveRecord::Base
end

breakfasts/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

breakfasts/app/controllers/breakfasts_controller.rb
class BreakfastsController < ApplicationController
  before_action :set_breakfast, only: [:show, :edit, :update, :destroy]

  # GET /breakfasts
  # GET /breakfasts.json
  def index
    @breakfasts = Breakfast.all
  end

  # GET /breakfasts/1
  # GET /breakfasts/1.json
  def show
  end

  # GET /breakfasts/new
  def new
    @breakfast = Breakfast.new
  end

  # GET /breakfasts/1/edit
  def edit
  end

  # POST /breakfasts
  # POST /breakfasts.json
  def create
    @breakfast = Breakfast.new(breakfast_params)

    respond_to do |format|
      if @breakfast.save
        format.html { redirect_to @breakfast, notice: 'Breakfast was successfully created.' }
        format.json { render :show, status: :created, location: @breakfast }
      else
        format.html { render :new }
        format.json { render json: @breakfast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breakfasts/1
  # PATCH/PUT /breakfasts/1.json
  def update
    respond_to do |format|
      if @breakfast.update(breakfast_params)
        format.html { redirect_to @breakfast, notice: 'Breakfast was successfully updated.' }
        format.json { render :show, status: :ok, location: @breakfast }
      else
        format.html { render :edit }
        format.json { render json: @breakfast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breakfasts/1
  # DELETE /breakfasts/1.json
  def destroy
    @breakfast.destroy
    respond_to do |format|
      format.html { redirect_to breakfasts_url, notice: 'Breakfast was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_breakfast
      @breakfast = Breakfast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def breakfast_params
      params.require(:breakfast).permit(:name, :description, :image_url, :date_tried)
    end
end

breakfasts/app/controllers/trail_mixes_controller.rb
class TrailMixesController < ApplicationController
  before_action :set_trail_mix, only: [:show, :edit, :update, :destroy]

  # GET /trail_mixes
  # GET /trail_mixes.json
  def index
    @trail_mixes = TrailMix.all
  end

  # GET /trail_mixes/1
  # GET /trail_mixes/1.json
  def show
  end

  # GET /trail_mixes/new
  def new
    @trail_mix = TrailMix.new
  end

  # GET /trail_mixes/1/edit
  def edit
  end

  # POST /trail_mixes
  # POST /trail_mixes.json
  def create
    @trail_mix = TrailMix.new(trail_mix_params)

    respond_to do |format|
      if @trail_mix.save
        format.html { redirect_to @trail_mix, notice: 'Trail mix was successfully created.' }
        format.json { render :show, status: :created, location: @trail_mix }
      else
        format.html { render :new }
        format.json { render json: @trail_mix.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trail_mixes/1
  # PATCH/PUT /trail_mixes/1.json
  def update
    respond_to do |format|
      if @trail_mix.update(trail_mix_params)
        format.html { redirect_to @trail_mix, notice: 'Trail mix was successfully updated.' }
        format.json { render :show, status: :ok, location: @trail_mix }
      else
        format.html { render :edit }
        format.json { render json: @trail_mix.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trail_mixes/1
  # DELETE /trail_mixes/1.json
  def destroy
    @trail_mix.destroy
    respond_to do |format|
      format.html { redirect_to trail_mixes_url, notice: 'Trail mix was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trail_mix
      @trail_mix = TrailMix.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trail_mix_params
      params.require(:trail_mix).permit(:name, :ingredients)
    end
end

breakfasts/app/helpers/application_helper.rb
module ApplicationHelper
end

breakfasts/app/helpers/breakfasts_helper.rb
module BreakfastsHelper
end

breakfasts/app/helpers/trail_mixes_helper.rb
module TrailMixesHelper
end

breakfasts/app/views/breakfasts/_form.html.erb
<%= form_for(@breakfast) do |f| %>
  <% if @breakfast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@breakfast.errors.count, " ") %> prohibited this breakfast from being saved:</h2>

      <ul>
      <% @breakfast.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :date_tried %><br>
    <%= f.date_select :date_tried %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

  <%= debug @breakfast.errors %>
<% end %>

breakfasts/app/views/breakfasts/edit.html.erb
<h1>Editing breakfast</h1>

<%= render 'form' %>

<%= link_to 'Show', @breakfast %> |
<%= link_to 'Back', breakfasts_path %>

breakfasts/app/views/breakfasts/index.html.erb
<div class="page-header">
<h1>Listing breakfasts <small>yum...</small></h1>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Date Tried</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @breakfasts.each do |breakfast| %>
      <tr>
        <td><%= breakfast.name %></td>
        <td><%= breakfast.description %></td>
        <td><%= image_tag breakfast.image_url, class: "thumb" %></td>
        <td><%= breakfast.date_tried %></td>
        <td><%= link_to 'Show', breakfast %></td>
        <td><%= link_to 'Edit', edit_breakfast_path(breakfast) %></td>
        <td><%= link_to 'Destroy', breakfast, class: 'btn btn-primary', method: :delete, data: { confirm: 'STAHP. Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Breakfast', new_breakfast_path %>

breakfasts/app/views/breakfasts/new.html.erb
<h1>New breakfast</h1>

<%= render 'form' %>

<%= link_to 'Back', breakfasts_path %>

breakfasts/app/views/breakfasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @breakfast.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @breakfast.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= image_tag @breakfast.image_url %>
</p>

<p>
  <strong>Date Tried:</strong>
  <%= @breakfast.date_tried %>
</p>

<%= link_to 'Edit', edit_breakfast_path(@breakfast) %> |
<%= link_to 'Back', breakfasts_path %>

breakfasts/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Breakfasts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

    <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

breakfasts/app/views/trail_mixes/_form.html.erb
<%= form_for(@trail_mix) do |f| %>
  <% if @trail_mix.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trail_mix.errors.count, "error") %> prohibited this trail_mix from being saved:</h2>

      <ul>
      <% @trail_mix.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br>
    <%= f.text_area :ingredients %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

breakfasts/app/views/trail_mixes/edit.html.erb
<h1>Editing trail_mix</h1>

<%= render 'form' %>

<%= link_to 'Show', @trail_mix %> |
<%= link_to 'Back', trail_mixes_path %>

breakfasts/app/views/trail_mixes/index.html.erb
<h1>Listing trail_mixes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ingredients</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trail_mixes.each do |trail_mix| %>
      <tr>
        <td><%= trail_mix.name %></td>
        <td><%= trail_mix.ingredients %></td>
        <td><%= link_to 'Show', trail_mix %></td>
        <td><%= link_to 'Edit', edit_trail_mix_path(trail_mix) %></td>
        <td><%= link_to 'Destroy', trail_mix, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trail mix', new_trail_mix_path %>

breakfasts/app/views/trail_mixes/new.html.erb
<h1>New trail_mix</h1>

<%= render 'form' %>

<%= link_to 'Back', trail_mixes_path %>

breakfasts/app/views/trail_mixes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @trail_mix.name %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @trail_mix.ingredients %>
</p>

<%= link_to 'Edit', edit_trail_mix_path(@trail_mix) %> |
<%= link_to 'Back', trail_mixes_path %>